app:
#  bootstrap_servers:
#    - broker-1:29092
#    - broker-2:39092
#    - broker-3:49092
  bootstrap_servers:
    - broker-1:19092
    - broker-2:19092
    - broker-3:19092
  topic: "weather"

location:
  name: "Area 51"
  lat: 37.2350
  long: -115.8111
  
apis:
  weather_url: "https://api.open-meteo.com/v1/forecast"
  telegram_url_template: "https://api.telegram.org/bot{bot_token}/{msg}"
  telegram_bot_token:  "123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11"
