app:
  bootstrap_servers: "localhost:9092"
  topic: "weather/topic"

location:
  name:
  lat:
  long:
  
apis:
  weather_url: "https://api.open-meteo.com/v1/forecast"
  telegram_url_template: "https://api.telegram.org/bot{bot_token}/{msg}"
  telegram_bot_token:  "123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11"
