app:
  bootstrap_servers: "localhost:9092"
  topic: "weather/topic"

location:
  name:
  lat:
  long:
  
apis:
  weather_url: "https://api.open-meteo.com/v1/forecast"
  telegram_url: "https://api.telegram.org/bot{bot_token}/{msg}"
